import axios from "axios";

export const FETCH_SMURF = "FETCH_SMURF";
export const FETCH_SMURF_SUCCESS = "FETCH_SMURF_SUCCESS";
export const FETCH_SINTGLE_SMURF = "FETCH_SINGLE_SMURF";
export const FETCH_SINGLE_SMURF_SUCCESS = "FETCH_SINGLE_SMURF_SUCCESS";
export const FETCH_SMURF_ERROR = "FETCH_SMURF_ERROR";
export const FETCH_SINGLE_SMURF_ERROR = "FETCH_SINGLE_SMURF_ERROR";
